project:
  type: book
  output-dir: docs


book:
  title: "Sequence Language Models & Deep Learning in Genomics"
  subtitle: "A book for those late to the AI party and trying to catch up."
  reader-mode: true
  author: "Michel Nivard"
  date: today
  navbar:
    search: true
    logo: DNA.png
    favicon: DNA.png
  chapters:
    - index.qmd
    - Preamble1.qmd
    - Preamble2.qmd
    - Preamble3.qmd
    - part: "DNA"
      chapters: 
        - Chapter1_DNA.qmd
        - Chapter2_DNA.qmd
        - Chapter3_DNA.qmd
        - Chapter4_DNA.qmd
        - Chapter5_DNA.qmd
        - Chapter6_DNA.qmd
    - Scaling_training.qmd    
    - part: "Proteins"
      chapters:
        - Chapter1_Proteins.qmd
        - Chapter2_Proteins.qmd
        - Chapter3_Proteins.qmd
        - Chapter4_Proteins.qmd
        - Chapter5_Proteins.qmd
    - part: "Multi-Modal-Biology"
    - summary.qmd
    - references.qmd

bibliography: references.bib

format: 
  html:
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 200px
    comments:
      utterances:
         repo: MichelNivard/Biological-language-models
    theme:
      - cosmo
      - style.scss



