project:
  type: book
  output-dir: docs


book:
  title: "Biological language models & Neural Networks"
  reader-mode: true
  author: "Michel Nivard"
  date: "2/27/2025"
  navbar:
    search: true
  chapters:
    - index.qmd
    - part: "DNA"
      chapters: 
        - Chapter1.qmd
        - Chapter2.qmd
        - Chapter3.qmd
        - Chapter4.qmd
        - Chapter5.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format: 
  html:
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 200px
    comments:
      utterances:
         repo: MichelNivard/Biological-language-models
    theme:
      - cosmo
      - style.scss



