project:
  type: book
  output-dir: docs

book:
  title: "Biological language models & Neural Networks"
  author: "Miche Nivard"
  date: "2/27/2025"
  chapters:
    - index.qmd
    - part: "DNA"
      chapters: 
        - Chapter1.qmd
        - Chapter2.qmd
        - Chapter3.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - lex



